version: '3.7'
services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbitmq"
    ports:
      - "15672:15672"  # Management Console
      - "5672:5672"    # RabbitMQ server
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - rabbitmq-net

networks:
  rabbitmq-net:
    driver: bridge
